# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Test and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    env:
        SOLUTION : 'MASTEK.INTERVIEW/MASTEK.INTERVIEW.sln' 
        BUILD_CONFIG : 'Release' 
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
      
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true

    - name: Run automated unit and integration tests
      run: dotnet test MASTEK.INTERVIEW/MASTEK.INTERVIEW.UNITTEST-X/MASTEK.INTERVIEW.UNITTEST-X.csproj  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: MASTEK.INTERVIEW/MASTEK.INTERVIEW.UNITTEST-X/TestResults/coverage.info 

    # - name: Test Report
    #   uses: dorny/test-reporter@v1
    #   if: always()
    #   with:
    #     name: DotNET Tests
    #     path: "**/test-results.trx"                            
    #     reporter: dotnet-trx
    #     fail-on-error: true
